### ISSUE TITLE
Dockerizing Flask

### ISSUE THREAD

**Issue by vigorem** [okomarov/dash_on_flask#1]
Hi, 

many many thanks for your precious repo. I managed to set everything up in my local system. I'm now trying to dockerize it but I'm facing some issues with it.

Dockerfile : 

	FROM python:3.6

	COPY . /app
	WORKDIR /app

	RUN pip install --upgrade pip
	RUN pip install -r requirements.txt

	CMD [ "source .envrc" ]
	CMD [ "flask run --host=0.0.0.0" ]

	# The EXPOSE instruction indicates the ports on which a container # # will listen for connections
	# Since Flask apps listen to port 5000  by default, we expose it
	EXPOSE 5000

Build 👍 works fine : 

    docker build . -t flask_image

Run however fails: 

    docker run --name flask_container -p 81:5000 flask_image

    >>docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"flask run --host=0.0.0.0\": executable file not found in $PATH": unknown.

Any suggestions would be of great help! 

Thanks,

Sébastien

**Comment by okomarov** [comment]
I haven't tried dockerizing it but it would be a nice addition. 

So, the repo currently has the following directory structure:

```
.
├── LICENSE
├── README.md
├── app
│   ├── __init__.py
│   ├── extensions.py
│   ├── forms.py
│   ├── models.py
│   ├── templates
│   └── webapp.py
├── app.db
├── config.py
├── dashapp.py
├── migrations
│   ├── README
│   ├── alembic.ini
│   ├── env.py
│   ├── script.py.mako
│   └── versions
└── requirements.txt
```

If you `flask run` from the `/app` subdir you will get this error:
<img width="987" alt="screenshot 2019-01-23 at 15 58 12" src="https://user-images.githubusercontent.com/3731173/51619218-c02ef800-1f27-11e9-8479-634c53237348.png">

You should `flask run` from the main directory. Let me know if this helps.

**Comment by vigorem** [comment]
My `Dockerfile` may have led to a confusion:

    COPY . /app
    WORKDIR /app

The app folder it is refering to is the root folder in docker:

	app
	├── LICENSE
	├── README.md
	├── app
	│   ├── __init__.py
	│   ├── extensions.py
	│   ├── forms.py
	│   ├── models.py
	│   ├── templates
	│   └── webapp.py
	├── app.db
	├── config.py
	├── dashapp.py
	├── migrations
	│   ├── README
	│   ├── alembic.ini
	│   ├── env.py
	│   ├── script.py.mako
	│   └── versions
	└── requirements.txt

Will change it to for more clarity:

    COPY . /dash_on_flask
    WORKDIR /dash_on_flask

I suspect that the following CMD doesn't do its job under docker:

     CMD [ "source .envrc" ]

**Comment by okomarov** [comment]
Sounds like it!

You can try to `RUN source .envrc` or you need to actually have and `.env` named file: https://docs.docker.com/compose/env-file/

**Comment by vigorem** [comment]
Solved it !

Changed my Dockerfile to:

	FROM python:3.6

	COPY . /dash_on_flask
	WORKDIR /dash_on_flask

	RUN  python -m venv venv
	CMD  ["source venv/bin/activate"]

	RUN pip install --upgrade pip
	RUN pip install -r requirements.txt

	RUN chmod +x startup.sh

	ENTRYPOINT ["/bin/bash", "startup.sh"]

	EXPOSE 5000

and added the following `startup.sh`script: 

    #!/bin/sh

    source .envrc
    source venv/bin/activate
    FLASK_APP=dashapp
    flask run --host=0.0.0.0


Many thanks

**Comment by olmax99** [comment]
Also thanks from my side.. I've dockerized your repo into production-ready project ( consisting of two projects ) .. you can find the REAME in the dockerdashflask:
https://gitlab.com/olmax99/dockerdashflask.git    <-- docker-compose wrapper
https://gitlab.com/olmax99/dashflask.git

It is based on the following project, and all explanations here apply as well:
https://github.com/tiangolo/meinheld-gunicorn-flask-docker

**Comment by okomarov** [comment]
@olmax99 Thanks for dockerizing, I will add the links to the readme. 

In the meantime, check out the update folder structure, with the Dash app in its own subfolder.

**Comment by al-yakubovich** [comment]
@okomarov
@olmax99 

Thanks for awesome project. I think docker part is really important.

I tried adocker version but it doesn't work for me. I ran:

```
$ docker-compose up -d --build
$ docker-compose exec web sh -c 'pipenv run flask run --host=0.0.0.0 --port=5000'
```

It says _Running on http://0.0.0.0:5000/_ but I am getting an error:

```
Unknown Host Description: Unable to locate the server named "0.0.0.0" --- the server does not have a DNS entry. Perhaps there is a misspelling in the server name, or the server no longer exists. Double-check the name and try again.
```

Tried to run on another laptop and got another error:

```
This site can't be reached
The webpage at http://0.0.0.0:5000/ might be temporarily down
```

**Comment by okomarov** [comment]
Added Docker support in https://github.com/okomarov/dash_on_flask/commit/13ef1f438aa6220db2c03b4d2a79c955cbd27178
