### ISSUE TITLE
Get current_user in Dash application

### ISSUE THREAD

**Issue by jenguehard** [okomarov/dash_on_flask#21]
Dear Oleg,

First of all congratulations on your awesome!

As many I've tried to access my flask_login username into my Dash applications. I've checked all the answers but I can't seem to make it work so I've started with your repo from scratch.

I am just trying to access on any of the dashapp files the username logged in with from flask_login import current_user but I'm only getting None answers.

Do you have any idea what I might change to get the username ?

Many thanks,

**Comment by okomarov** [comment]
I'll try to have a look in the coming days. Feel free to ping me again if you don't see any progress after end of week.

**Comment by okomarov** [comment]
@jenguehard I pushed a new commit that shows a workaround to save the username into a store and a simple component that updates depending on the changes to the store 

You can also just pass the content of the store as State. It's not optimal but it does the job.

**Comment by jenguehard** [comment]
Dear @okomarov , thank you very much for your help !
