### ISSUE TITLE
Redirect to dashapp after login

### ISSUE THREAD

**Issue by wielrenner** [okomarov/dash_on_flask#3]
I would like to go automatically to the dashapp after login, but I'm struggling to make it work.

Can you give some help on what to change?

**Comment by okomarov** [comment]
@wielrenner You might have already solved since you closed but it could be useful to others too.

We define:
```python
dashapp = dash.Dash(__name__, server=server, url_base_pathname='/dashboard/')
```
Your route will have to use the full `url_base_pathname`. I have not found an anlternative way:
```python
redirect(url_for('/dashboard/'))
```
