### ISSUE TITLE
dash app loading forever

### ISSUE THREAD

**Issue by joejztang** [okomarov/dash_on_flask#4]
follow along with the medium post you posted.

great implementation!

however, I don't know if it just me or anybody else is with me. once login, goes to /dashboard/, the page shows 'loading', and it stuck there.

any hint is appreciate.

**Comment by joejztang** [comment]
I built a native dash app to compare with your version. I found at runtime, there is one thing missing at the footer

`<script id="_dash-renderer" type="application/javascript">var renderer = new DashRenderer();</script>`

**Comment by joejztang** [comment]
I just did a version not using factory pattern and works. I think the reason is dash framework ask for `app.run_server()` called before this application runs.
in your code, I think you didn't call this, that is possible reason for loading forever.

**Comment by okomarov** [comment]
I’ll check this weekend and get back to you.

**Comment by okomarov** [comment]
@joejztang I updated the dependencies in the requirements.txt and the problem is now fixed. It was failing to load some .js from the CDN porbably due to discrepancies in the unpinned requirements.

Please lastest master commit and upgrade requirements with:
```
pip install -r requirements.txt --upgrade
```

**Comment by joejztang** [comment]
great, work as it should be. hats off :) 💯
