### ISSUE TITLE
Where to put db.create_all()?

### ISSUE THREAD

**Issue by OlafHaag** [okomarov/dash_on_flask#5]
Hi and thanks for your template which I try to follow more or less [here](https://github.com/OlafHaag/UCM-WebApp). But I can't figure out where to put db.create_all() or how to use it to create the tables in the database from the models.

I use a PostgreSQL database and tried putting it into app.\_\_init\_\_:register_extensions:
```python
def register_extensions(server):
    from app.extensions import db
    from app.models import User
    db.init_app(server)
    with server.app_context():
        # Create tables for our models.
        db.create_all()
```
Unfortunately I get an OperationalError when doing this, even though I set my _DATABASE_URL_. I also tried with an adhoc _sqlite:///mydb.db_ and didn't get an error, but it did seem to be empty (no tables) after running the app.

How did you create your database from the model in the example?
Or how would you do it using the commandline?

**Comment by okomarov** [comment]
This is a one time operation.

In local before `flask run`:

```
flask db init
flask db migrate -m 'init'
flask db upgrade
```

On Heroku you will need to use the [manager](https://flask-migrate.readthedocs.io/en/latest/#using-flask-script) and form  `run console > bash`:
```
python manage.py db init
python manage.py db upgrade
```

Then you could add to the procfile:
```
release: python manage.py db upgrade
```
so that you get the upgrades on each deploy.

Where manage.py is:
```
from flask_migrate import MigrateCommand
from flask_script import Manager

from app import app


manager = Manager(app)
manager.add_command('db', MigrateCommand)

if __name__ == '__main__':
    manager.run()
```

**Comment by OlafHaag** [comment]
Thanks for the quick reply and the detailed information! Good to know.
I'll try to make it work with the built-in cli in flask. It should have the _db_ command and my intuition is that I could forego the manage.py file with the extra dependency on _flask_script_.

As for the OperationalError: it turned out that I just didn't give my user permission to login...

**Comment by okomarov** [comment]
If you manage to avoid the `manage.py` on Heroku let me know how you did it!

**Comment by OlafHaag** [comment]
My intuition luckily turned out to be right.
I only had to import the models before the migrate, so the _register_extensions_ function looks like this:
```python
def register_extensions(server):
    from app.extensions import db
    # We need to import the models for migration to detect them.
    from app.models import User
    from app.extensions import migrate

    db.init_app(server)
    migrate.init_app(server, db)
```
I followed your instructions for the __local__ setup and pushed the resulting _migrations_ folder to the repository.
I  actually don't know if it was necessary, but on heroku I set the __FLASK_APP__ environment variable, in my case to _wsgi.py_, for your template probably _dashapp:server_.
Then on heroku the only thing left was to `flask db upgrade`. I was able to confirm that all tables were created.

Thanks again! I really appreciate it.
