### ISSUE TITLE
Can not get css to work.

### ISSUE THREAD

**Issue by David-Frick** [okomarov/dash_on_flask#8]
I cannot seem to get CSS files to work. I have the static folder at the same level as templates. I am trying a simple example where I can the menu colors, for example. any advice?

**Comment by okomarov** [comment]
Hi David, 
To add your own CSS to a Flask app:

```

**Comment by okomarov** [comment]
If you want to add CSS to your dashapp, you can adopt one of the strategies explained under https://dash.plot.ly/external-resources

An example with a local CSS per dash app with folder structure:

```
app
├── dashapp1
│   ├── assets
│   │   └── dashstyle.css
├── __init__.py
...
```
where then in `__init__.py` each dashapp is initialised with:
```
my_dashapp = dash.Dash(__name__,
                           server=app,
                           url_base_pathname=f'/{base_pathname}/',
                           assets_folder=get_root_path(__name__) + f'/{base_pathname}/assets/')
```
where the `base_pathname` is the endpoint at which the dashapp is available, e.g. `http://127.0.0.1:5000/my_cool_dashapp`, so the `base_pathname` is `my_cool_dashapp`

**Comment by okomarov** [comment]
Feel free to reopen if this did not help.

**Comment by David-Frick** [comment]
Much appreciated. Thanks for the help!

**Comment by David-Frick** [comment]
Sorry for commenting after close. I realized I do not have any code to then use the `dashstyle.css` file in my code. Does the app.layout code need some sort of use this css file to work? Thanks.

**Comment by okomarov** [comment]
My second example shows how to let the Dash know where to look for external CSS. After that it's how you specify the CSS rules inside the css file that apply or not the style. You will have to then double check with your Chrome/Firefox dev tools to see if the rules are applied etc...

**Comment by David-Frick** [comment]
So I got it to work with the following code in the `__init__.py` file:
```
    dashapp1 = dash.Dash(__name__,
                         server=app,
                         url_base_pathname='/dashboard1/',
                         assets_folder=get_root_path(__name__) +
'/dashapp1/assets/',
                         meta_tags=[meta_viewport])
```
I read their documentation about how the __name__ variable in the Dash
constructor is where is looks for the css and so it was important to
specific the `dashapp1` folder so its knows the css is one file deeper.
Have a good one.

**Comment by okomarov** [comment]
Yep, that's right. When I mentioned the `f'/{base_pathname}/'` I should have given a concrete example.

**Comment by glw** [comment]
I thought I would mention here that, I got dash bootstrap components to work with a few minor alterations.

```python
# layout.py

layout = html.Div([navbar, body])
```

```python
# __init__.py

import dash_bootstrap_components as dbc
...
my_dashapp = dash.Dash(__name__,
                           server=app,
                           url_base_pathname=f'/{base_pathname}/',
                           assets_folder=get_root_path(__name__) + f'/{base_pathname}/assets/',
                           meta_tags=[meta_viewport],
                           external_stylesheets=[dbc.themes.BOOTSTRAP])
```

One question I had - unrelated to CSS, was should 
```my_dashapp.scripts.config.serve_locally = False``` be added to the init file?
